matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode8.3
addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt58-trusty
    packages:
    - qt58-meta-minimal
    - mesa-common-dev
    - libgl1-mesa-dev
    - libsqlite3-dev
    - libmysqlclient-dev
    - libssl1.0.0
    - libssl-dev
before_install:
- "./ci/travis/before_install_${TRAVIS_OS_NAME}.sh"
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt*/bin/qt*-env.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source qt-5.env; fi
- qmake -r
- make -j2
- make INSTALL_ROOT=appdir install
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./make_dist_linux.sh "src/maven/appdir/bin/Maven";
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./make_dist_osx.sh "src/maven/appdir/bin/Maven.app";
  fi
- ls -la dist/
deploy:
  provider: releases
  api_key:
    secure: zGEKsqNGwIuXVrXH+2jGdOfkDX9OUfT4Svg6PTouIAXyQPqNrujBwN6lg0RICtBDzZpPldepLVbeTmY3NOnZssXmbzYaheehmY2skfwA9Pb7+GR0EdjypZgzNMSiKtaPDx9dM+J2C1P2uxlLXQsJxNkxPrCCaSajb7SM1eRvpAZ8IwBp9VcPDq64n8crMXe+LHVo5d9FpFgaaRX167paqvG7TUfQSTljFVKzrYgyvl9iPoWjLuER4cMO1oO24KjL2RFpCdrMpGxI/DOgRdUK6DqBZZSc28fQvcRF3teXOTy+yxoGHCb/SeaA2WyC37c9zjr4h8186FGN9xYvkGU2TDl9pRigdKJTC5vfkLPZMSBOszULkZMnieGQJ1c2VNnFHzqRc1W2mdyBn9AKKZCEThkDqkWBVpsz3vhgLKUYG2w+ln3tYGPCbAviqo/KLQ2uYJ0iyCoPmm3M+mUOcU4D9mB3rOSKXJzD/7aUQR+V/WUYGseOBN51BYFATY10r4JU9RwTlqhw8xEry6rVycBUJcsYA4Gl6AMbNEc2MNKUfJeOZEtFRuBKNeA3pk+cbVi9AZLqVwWb3ShmpChZEdLLBUU9WDpn4iueywicr2o/FnThQKTWbVRSQa1IK1lV7G9VxfFokRG0NIk+1nZ/2em4a5FpuPKQQNPxpUA0nlzO+3U=
  file_glob: true
  file:
      - dist/Maven*.AppImage
      - dist/Maven*.dmg
  skip_cleanup: true
  on:
    repo: eugenemel/maven
    branch: master
    tags: true
